### ISSUE TITLE
Error when trying to check out

### ISSUE THREAD

**Issue by nikhil-1911** [medusajs/nextjs-starter-medusa#118]
![image](https://user-images.githubusercontent.com/131291664/233930444-8c7d2faf-3afe-4b6e-8058-de7e902c7243.png)
Getting this error in /checkout page. I have configured test stripe public key as well as secret in medusa admin. 
Can you please look into this? Thanks!

**Comment by kasperkristensen** [comment]
Hi @nikhil-1911,

Can't replicate the issue when testing on the latest version of the main branch. Have you made any customizations to the storefront?

**Comment by felipemullen** [comment]
I came across this issue as well. From my understanding it happens when the stripe component is remounted incorrectly, caused by the implementation of the [stripe react package](https://www.npmjs.com/package/@stripe/react-stripe-js). 

I ended up fixing it by adding the `key` prop to the `Elements` component inside `StripeWrapper` in `storefront/src/modules/checkout/components/payment-wrapper/index.tsx`:

```typescript
const StripeWrapper: React.FC<WrapperProps> = ({ paymentSession, children }) => {
    const clientSecret = paymentSession!.data.client_secret as string | undefined;
    const options: StripeElementsOptions = {
        clientSecret
    };

    return (
        <Elements stripe={stripePromise} options={options} key={clientSecret}>
            {children}
        </Elements>
    );
};
```
