### ISSUE TITLE
slowly navigate to produts

### ISSUE THREAD

**Issue by Adamkaram** [medusajs/nextjs-starter-medusa#129]
i had an issue and declared it in isuues section as a bug 
my main issue was 
slowly navigate to produts like 2 seconde to navigte 
and carts section doesn't work well!
 
4 request has been made for navigation to a product and that's a lot 
![Screenshot 2023-06-18 115002](https://github.com/medusajs/medusa/assets/52092726/3fbfeec7-8d6d-425a-af99-701a4898578b)

cart isn't working probably
![Screenshot 2023-06-18 115752](https://github.com/medusajs/medusa/assets/52092726/588e9faa-0918-49dd-8e09-423d8448584f)

401 status code for every navigate sometimes happens and sometimes not !
![Screenshot 2023-06-18 115849](https://github.com/medusajs/medusa/assets/52092726/9bfa323b-2bf3-49ef-9e53-ab709a94ab4a)

i'm working on 
windows 10 
latest node version 
latest project version

**Comment by kasperkristensen** [comment]
Hi @Adamkaram

You are running the starter in dev mode, most of these requests aren't made in production, as pages a statically generated, but while Next is running in dev mode pages are generated on each navigation. Page navigations should not take 2 seconds, and do not in my case, but could be related to the specs of your computer. This would again also be improved greatly once you run everything in production. Generally, you shouldn't judge performance on a dev build, but instead on the production build, to test this you can try to build the project and serve the build output.

I am not sure what you mean by the cart isn't working, it works fine on my end. Please provide actual information (error logs) if you have an issue so that we are able to help you. 

The `401` is expected, it checks if the user is logged in, and since you are not it returns a `401`.

I am closing this, as I see no actual issues in what you describe, if you have issues with the cart not working, then please open another issue and provide us with some error logs. 🙂
