### ISSUE TITLE
Unhandled Runtime Error Error: Could not find Elements context; You need to wrap the part of your app that mounts <CardNumberElement> in an <Elements> provider.

### ISSUE THREAD

**Issue by wadinggg** [medusajs/nextjs-starter-medusa#211]
<img width="1092" alt="Screenshot 2023-11-26 at 19 41 12" src="https://github.com/medusajs/nextjs-starter-medusa/assets/106756224/acf2727c-ecf8-4d43-b5be-4977aa360bd8">

**Comment by tabilzad** [comment]
#206 doesnt seem to fix it for me. Still getting an undefined paymentSession. Could it be because of the redundant `setPaymentSession` exposed from the `useCheckout` but not used in Payment which has its own `setPaymentSession`.  Also the `selectedProviderId` is passed to the StripeWrapper but not being used. The use memo added in #206 seems to just couple the selectedPaymentOptionId and cart?.payment_session?.provider_id why not just have a single source of truth?

**Comment by bqst** [comment]
@tabilzad +1

**Comment by luluhoc** [comment]
I see your problem now the problem was resolved for me cause I was using the unified all in one stripe iframe. I will try to make a fix tomorrow ;)

**Comment by VariableVic** [comment]
Should be fixed in https://github.com/medusajs/nextjs-starter-medusa/pull/218. Lmk if it solves your issues!
