### ISSUE TITLE
Dark mode incompatibility 

### ISSUE THREAD

**Issue by xyzones** [medusajs/nextjs-starter-medusa#253]
With `tailwindcss>3.3.3`, the design breaks during active dark mode.

<img alt="light" src="https://github.com/medusajs/nextjs-starter-medusa/assets/1039118/cd77452e-fb57-48ee-968a-91bdd1e75e01" width="200">
<img alt="dark" src="https://github.com/medusajs/nextjs-starter-medusa/assets/1039118/181a73b0-1d68-47ea-becd-387360c56ffe" width="200">

**Comment by fuse-thanakorn** [comment]
I got the same problem, any update ?

**Comment by VariableVic** [comment]
The Starter doesn't support dark mode, so any `dark:` classes present are leftovers from an early version.

I can't replicate the issue with the package versions you mentioned. What browser are you using?

**Comment by fuse-thanakorn** [comment]
@VariableVic  For me Safari and Chrome still got that same problem.

**Comment by Bernix01** [comment]
For me this issue happened when I updated tailwind above 3.3.3 as the issue description says

**Comment by ericwaetke** [comment]
I’ve got the same problem even with 2.4.1.
And I also don’t think it’s any `dark:` leftovers, as there are no dark: classes in the code.

However, there is a layout.css file being generated, that sets the color variables based on the css `prefers-color-scheme: dark` setting.

![Bildschirmfoto 2024-02-26 um 15 34 24](https://github.com/medusajs/nextjs-starter-medusa/assets/8260492/d5c5d1a4-f916-435a-84ca-1beb9aa815ae)

It’s because the [ui-preset tailwind plugin](https://github.com/medusajs/medusa/blob/b13c669528ecd2940a46d6fe5985ef622048879a/packages/design-system/ui-preset/src/plugin.ts) is looking at the config to see, if the `darkMode: 'class'` property is set in the `tailwind.config.js`. If not (as it is by default), it overrides the color variables based on the system color scheme.

So you can fix it by explicitly saying the dark-mode isn’t set based on the system:
```js
module.exports = {
  darkMode: 'class',
  presets: [require("@medusajs/ui-preset")],
  …
}
```

I could also create a PR to make this the default behaviour for freshly created nextjs-starters, if that’s wanted

**Comment by VariableVic** [comment]
@ericwaetke great catch, I'd happily accept that PR!

**Comment by xyzones** [comment]
I don't think you understand the problem. We need to darkMode and it is simply not working.

**Comment by VariableVic** [comment]
> We need to darkMode and it is simply not working.

What do you mean exactly? Are you trying to add `dark:` classes and they aren't picking up? Please elaborate on what you're trying to  achieve and what is not working as expected.

**Comment by xyzones** [comment]
@VariableVic just look the original post pictures with darkmode the whole store is unusable

**Comment by VariableVic** [comment]
Like I said, this Starter doesn't support dark mode out of the box. It's light mode only. There's 2 things you can do here:

1. Implement @ericwaetke's fix to prevent the store from switching to dark mode entirely. This will enforce light mode regardless of the user settings.
2. Or, if you want to use dark mode: implement it yourself.  You can use [Medusa UI classes](https://www.figma.com/community/file/1278648465968635936/medusa-ui) like `bg-ui-bg-base` - they will switch based on the user system setting. As you can see in your screenshot, some components are already using these, and thus reacting to dark mode.

**Comment by xyzones** [comment]
@VariableVic so no intention to make this available? I have solved this went I opened, so is not really affecting me, however this would be surely much appreciated by the community ;)

**Comment by VariableVic** [comment]
It's not a priority as of now, but we might add it later. Feel free to add it as an idea to GH discussions!
