### ISSUE TITLE
Final checkout amount to pay not up to date with Paypal

### ISSUE THREAD

**Issue by Lynx-D** [medusajs/nextjs-starter-medusa#260]
Hi, there is an issue with the paypal plugin integration, paypal get the request of the amount authorization too early during the checkout process. For example, when I order a product that cost me CA$30.78, I will add a shipping method that will cost me CA$9.99 but on the Paypal payment modal it will say that I have to pay only CA$30.78 instead of CA$40,77, because the amount hasn't been updated on Paypal.

Is their a solution for this or do I have to rewrite the checkout process ?

**Comment by VariableVic** [comment]
Hey @Lynx-D,

I tried to reproduce your issue, but it seems to work as expected in my local environment.

Steps I took:

- Clear cache and cookies.
- Set region / currency to Canada + CAD.
- Add item to cart.
- Enter checkout.
- Add shipping method (CAD 9,99)
- Set PayPal as payment method
- Click PayPal button and enter my email.

This resulted in a PayPal modal with the exact same total as my cart in checkout:

![Screenshot 2024-02-12 at 12 22 49](https://github.com/medusajs/nextjs-starter-medusa/assets/42065266/daedb100-2cd9-4fd3-8fd8-f3ca26d94ae1)

Could you provide the detailed steps needed to reproduce this issue?

**Comment by raiyansarker** [comment]
@VariableVic, I followed this [guide](https://docs.medusajs.com/plugins/payment/paypal), I am not sure how paypal understand how much to charge as I am just providing client id in the frontend. Am I missing something?

**Comment by raiyansarker** [comment]
I think it is due to not add `createOrder` callback in paypal button. If I am right then the docs should mention it, otherwise @VariableVic, can you share your code?

**Comment by VariableVic** [comment]
@raiyansarker I think you might be right about the `createOrder` callback missing in the docs example.

[Here](https://github.com/medusajs/nextjs-starter-medusa/blob/5c372f7ee28161ba6fbb12d80e4a3a0e0e4b8c9d/src/modules/checkout/components/payment-button/index.tsx#L137) is the code I use. I'm passing the payment session id in the `createOrder` callback, and the Medusa plugin takes care of providing the order details to PayPal.

**Comment by raiyansarker** [comment]
@VariableVic I am not sure whether I should ask this question here but what are the events that should be selected for paypal?

**Comment by VariableVic** [comment]
@raiyansarker I'm not sure what events you're referring to, could you elaborate?

**Comment by raiyansarker** [comment]
> @raiyansarker I'm not sure what events you're referring to, could you elaborate?

webhook events

**Comment by manuel-schoebel** [comment]
I have a similar issue.

I create a cart. No shipping option selected. I create the PayementSession. I assume this initiates the payment on paypal, but without shipping costs.

Then i set a shipping option - the carts total changes.

When I then pass the payment_session.data.id to the createOrder fn of the PayPalButtons it gets the paypal event id of the earlier created one, without shipping cost. So the redirect to paypal shows the wrong one without shipping cost.

If i create the paymentSession only after the shipping was selected it does work correctly.

But the problem is, that whenever I create a new PaymentSession i get the old payment session id.

So ideally when creating a payment session it always creates a new one, but does not return the old one. 

Maybe it is some caching issue with next. Or the paypal plugin does not create a new one if it already has one or does not update it on paypals side if the cart changes (if that is at all possible) 🤔

**Comment by ximenadev** [comment]
@manuel-schoebel @raiyansarker @VariableVic did you were able to fix this?

I'm having the same issue of not getting the shipping cost on PayPal. It also happens if I start the checkout flow and then go back to add more products.
