### ISSUE TITLE
Unable to Login to Admin Panel in Production Environment after Vercel Deploy - Possible CORS and Database Connection Issue

### ISSUE THREAD

**Issue by crnls** [medusajs/nextjs-starter-medusa#273]
### Issue Description:
I have encountered an issue where I am able to successfully deploy the admin interface to Vercel but am unable to log in after. This problem seems to be related to a mistake in the CORS settings or the database connection. While everything works fine locally, the database connection appears to be malfunctioning in the production environment.

Console:
see attachment
<img width="1376" alt="Scherm­afbeelding 2024-02-20 om 16 44 52" src="https://github.com/medusajs/nextjs-starter-medusa/assets/18337971/8a929ce7-ef16-45b5-a2b6-c03920392047">

#### Configuration Details:

- **ADMIN_CORS**
  - Environments: Development, Preview, Production
  - Value:  https://admin.wantsandneeds.nl

- **STORE_CORS**
  - Environments: Development, Preview, Production
  - Value: `/https?:\/\/.+/` (Regex pattern to allow all HTTPS URLs)

- **COOKIE_SECRET**
  - Environments: Development, Preview, Production
  - Value: `secret`

- **JWT_SECRET**
  - Environments: Development, Preview, Production
  - Value: `secret`

- **DATABASE_TYPE**
  - Environments: Development, Preview, Production
  - Value: `postgres`

- **MEDUSA_ADMIN_BACKEND_URL**
  - Environments: Development, Preview, Production
  - Value: https://admin.wantsandneeds.nl

- **DATABASE_URL**
  - Environments: Development, Preview, Production
  - Value: `SUPABASEURISTRING`

**Comment by VariableVic** [comment]
I don't see anything wrong with that setup.

- Is your store API working properly? E.g. GET <MEDUSA_URL>/store/products
- Are you sure the user account exists on the live db?
- Can you try to [create a new user](https://docs.medusajs.com/admin/quickstart#create-a-new-admin-user) and see if the issue persists?

If you're sure about the credentials and the issue persists, I'd suggest posting this at the [main repo](https://github.com/medusajs/medusa) as it's not related to this Starter project.

**Comment by kevinrobert3** [comment]
I have had this problem since yesterday and had to go back to the drawing board on what is the admin, backend and storefront. I think the Medusa team can correct me if I am wrong. [Link to Doc](https://docs.medusajs.com/deployments).

The gist is the deployment you have made is the 'admin' only. 

The backend is not up. This is where you get the backend url e.g heroku.url, d-ocean.url the place where your backend is running. 
Vercel in itself cannot host the backend, again correct me if I am wrong here, but it hosts the 'frontend' of the admin part.

As it is you are trying to connect to the backend but it is not on Vercel. Correct me if I am getting this right. This https://admin.wantsandneeds.nl/ is just the frontend of the admin with a vanity url saying 'admin'. The backend url should be retrieved from another provider. Unless I am way off too. 

And I think the Medusa team should do more official intro videos into the product from the start (creation) to the end, deployment. There is one on Netlify but the backend part is left out

**Comment by crnls** [comment]
@kevinrobert3 So yesterday I also thought of this, but it wouldnt make any sense that they have this [Deploy admin to Vercel guide](https://docs.medusajs.com/deployments/admin/deploying-on-vercel) up without mentioning anywhere that the backend needs to be hosted somewhere else in tandem. 

Do you now have everything set up? Then I'll just try to follow the route with the backend on heroku and rest on vercel

**Comment by kevinrobert3** [comment]
I decided to use local first, with databases online on supabase. Everything is working. 

A good example is the Admin on local starts up on `localhost:7001` (browser), but the calls to backend api e.g login, on the NextJs Storefront and the Admin itself go to `localhost:9000` where the backend is running on. 

And for some reason, Medusa does not print out (mention) anything in the terminal about this "server" that has been started on port 9000. You have to go deep in docs and find that a server gets started

I'll host the backend much later, for now, i'll be on local only

**Comment by edocollado** [comment]
In the end, is the best option not to host the backend on Vercel?

**Comment by crnls** [comment]
Yes, I ended up moving it to Heroku. I don’t think it’s possible through Vercel (only admin/front end).
Groet,
Martijn van der Pas

Op 8 apr 2024 om 19:00 heeft Eduardo Collado ***@***.***> het volgende geschreven:

﻿

In the end, is the best option not to host the backend on Vercel?
