### ISSUE TITLE
The store works in dev mode(yarn dev), but does not compile for production(yarn buld).

### ISSUE THREAD

**Issue by og-dev** [medusajs/nextjs-starter-medusa#352]
OS: Ubuntu 20.04
Node: 18.18.0

Fail due **Type error: Parameter 'c' implicitly has an 'any' type.**

```
yarn run v1.22.22
$ next build
next.config.js {}
  ▲ Next.js 14.2.5
  - Environments: .env.local

   Creating an optimized production build ...
next.config.js {}
next.config.js {}
next.config.js {}
 ✓ Compiled successfully
   Linting and checking validity of types  ...Failed to compile.

./src/modules/checkout/components/shipping-address/index.tsx:37:39
Type error: Parameter 'c' implicitly has an 'any' type.

  35 |
  36 |   const countriesInRegion = useMemo(
> 37 |     () => cart?.region.countries.map((c) => c.iso_2),
     |                                       ^
  38 |     [cart?.region]
  39 |   )
  40 |
error Command failed with exit code 1.
```

if strict is disbled in tsconfig then:  **Linting and checking validity of types  ..Failed to compile.**

```
store-storefront# yarn build
yarn run v1.22.22
$ next build
next.config.js {}
  ▲ Next.js 14.2.5
  - Environments: .env.local

   Creating an optimized production build ...
next.config.js {}
next.config.js {}
next.config.js {}
 ✓ Compiled successfully
   Linting and checking validity of types  ..Failed to compile.

./src/app/[countryCode]/(main)/cart/page.tsx:37:3
Type error: Type '"" | "address" | "delivery" | "payment"' is not assignable to type '"address" | "payment" | "delivery"'.

  35 |   }
  36 |
> 37 |   cart.checkout_step = cart && getCheckoutStep(cart)
     |   ^
  38 |
  39 |   return cart
  40 | }
error Command failed with exit code 1.

```
Is there a way to fix those error?

I tried to fix the second error by changing @types/react, @types/react-dom but it did not work

**Comment by adambarath** [comment]
I had the same issue. See my comment at: https://github.com/medusajs/nextjs-starter-medusa/issues/279#issuecomment-2359983247

**Comment by VariableVic** [comment]
Should be fixed with the Next.js 15 update. Closing this for now.

**Comment by dapinitial** [comment]
**Running Node v23 and NPM v10.9.1**

I am trying to deploy the frontend to Azure Container using Docker. Backend builds and deploys no issues, but when building the storefront I am getting this issue... Maybe related to this post?

  ▲ Next.js 15.0.3
   - Environments: .env.local

   Creating an optimized production build ...
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
 ✓ Collecting page data
Failed to build /[countryCode]/(main)/categories/[...category]/page: /es/categories/sweatshirts (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.
Failed to build /[countryCode]/(main)/categories/[...category]/page: /es/categories/pants (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.
Failed to build /[countryCode]/(main)/categories/[...category]/page: /es/categories/merch (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.
Failed to build /[countryCode]/(main)/categories/[...category]/page: /fr/categories/sweatshirts (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.
Failed to build /[countryCode]/(main)/categories/[...category]/page: /fr/categories/pants (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.
Failed to build /[countryCode]/(main)/categories/[...category]/page: /fr/categories/merch (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.
Failed to build /[countryCode]/(main)/categories/[...category]/page: /de/categories/sweatshirts (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.
Failed to build /[countryCode]/(main)/categories/[...category]/page: /de/categories/pants (attempt 1 of 3) because it took more than 300 seconds. Retrying again shortly.

**Comment by ozbrandcc** [comment]
Im getting the same error, any new?
