### ISSUE TITLE
npm error Found: react@19.0.0-rc-66855b96-20241106

### ISSUE THREAD

**Issue by RoxDevvv** [medusajs/nextjs-starter-medusa#422]
To reproduce, simply clone the repository and run `npm install`.

```
An error occurred while installing Next.js storefront: Error: Command failed: npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: medusa-next@1.0.3
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">=16.8.0" from @hookform/error-message@2.0.1
npm error node_modules/@hookform/error-message
npm error   @hookform/error-message@"^2.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by VariableVic** [comment]
Hey @RoxDevvv,

This is due to Next.js 15 requiring React 19, but some dependencies have yet to update their supported React versions.

There's two ways to bypass this error:

1. Run `npm install --legacy-peer-deps` to bypass the error. This won't break the app afaik.
2. Use either Yarn or PNMP as a package manager, as they don't have this issue.

It's a bit of an annoying in-between state, sorry for that. Should be good as soon as all packages add React 19 as a peer dependency.

I've removed the `@hookform/error-message` package btw, as it's no longer used. But there will be other packages throwing the same error.

Closing this for now, let me know if you have any questions.

**Comment by ensidialabs** [comment]
@VariableVic Now, as I understand, it is not possible to install backend + storefront together using npx create-medusa-app@latest. We install backend and then clone the directory with storefront and install storefront using pnpm. Is this the way?

**Comment by VariableVic** [comment]
Hey @ensidialabs, I just merged a fix to main. `npm install` and `npx create-medusa-app@latest` should now work again. Could you please give it a spin and let me know if your issue is fixed?

**Comment by ensidialabs** [comment]
@VariableVic fixed. Thank you! Everything ok now
