### ISSUE TITLE
401 Unauthorized on  /store/customers/me

### ISSUE THREAD

**Issue by rohan-mm** [medusajs/nextjs-starter-medusa#63]
On page loads, I always get this error. How do I remove it?

`ET http://localhost:9000/store/customers/me 401 (Unauthorized)`

![image](https://user-images.githubusercontent.com/92304223/185433042-a8d32edf-31db-450d-ab6a-b458e9a2ce73.png)

**Comment by kasperkristensen** [comment]
The error occurs because of this line of code: https://github.com/medusajs/nextjs-starter-medusa/blob/06c7381c9596897f1dfe01f592690cf81ae2791e/src/lib/context/account-context.tsx#L26-L30. It checks if the user is logged in and if they are not, then it will obviously fail. You could update the logger of React Query to prevent the errors being printed to the console – https://tanstack.com/query/v4/docs/guides/custom-logger :)

**Comment by omararturo** [comment]
This problem continue
